import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { log } from "../util/log.js";
import { resolveCredential } from "../auth/appsheet.js";

interface Evaluatable {
  SourceExpr?: string;
  EvalType?: string;
  $type?: string;
}

interface RawAttribute {
  Name: string;
  Type?: string;
  TypeAuxData?: string;
  Description?: string;
  DisplayName?: string;
  IsKey?: boolean;
  IsKeyPart?: boolean;
  IsRequired?: boolean;
  IsHidden?: boolean;
  IsVirtual?: boolean;
  IsReadOnly?: boolean;
  IsLabel?: boolean;
  IsAutoGenerated?: boolean;
  IsSensitive?: boolean;
  Searchable?: boolean;
  Default?: string | null;
  DefaultExpression?: Evaluatable | null;
  Formula?: string | null;
  AppFormula?: Evaluatable | null;
  ResetOnEdit?: boolean;
  IsScannable?: boolean;
}

interface RawSchema {
  Name: string;
  AutoSchemaFrom?: string;
  Attributes?: RawAttribute[];
}

interface RawDataset {
  Name: string;
  TableName?: string;
  KeyName?: string;
  LabelName?: string;
}

interface RawAction {
  Name: string;
  DisplayName?: string;
  ActionType?: string;
  Table?: string;
  TableScope?: string;
  Scope?: string;
  Icon?: string;
  ColumnToEdit?: string;
  Comment?: string;
  Inputs?: unknown[];
  Value?: string | null;
  ValueEvaluatable?: Evaluatable | null;
  Condition?: string | null;
  ConditionEvaluatable?: Evaluatable | null;
  ActionSettings?: Record<string, unknown>;
  ActionDefinition?: Record<string, unknown>;
}

interface RawControl {
  Name: string;
  DisplayName?: string;
  TableOrFolderName?: string;
  ActionType?: string;
  Position?: string;
  Description?: string;
  ShowIf?: string | null;
  Parameters?: Record<string, unknown>;
  Settings?: Record<string, unknown>;
  ViewDefinition?: Record<string, unknown>;
}

interface RawApp {
  Id: string;
  Name?: string;
  ShortName?: string;
  Title?: string;
  Description?: string;
  Version?: string;
  AppData: {
    DataSets?: RawDataset[];
    DataSchemas?: RawSchema[];
    DataActions?: RawAction[];
  };
  Behavior: {
    AppBots?: unknown[];
    AppWorkflowRules?: unknown[];
    AppEvents?: unknown[];
    AppProcesses?: unknown[];
  };
  Presentation: {
    Controls?: RawControl[];
    MenuEntries?: unknown[];
  };
}

const cache = new Map<string, RawApp>();

function snapshotPath(appId: string): string {
  return resolve(process.cwd(), "snapshots", `appdef-${appId}.json`);
}

async function loadFromFile(filePath: string): Promise<RawApp> {
  const text = await readFile(filePath, "utf8");
  return JSON.parse(text) as RawApp;
}

async function ensureLoaded(appId: string, explicitPath?: string): Promise<RawApp> {
  if (!explicitPath && cache.has(appId)) return cache.get(appId)!;
  const path = explicitPath ? resolve(explicitPath) : snapshotPath(appId);
  if (!existsSync(path)) {
    throw new Error(
      `app definition スナップショットが見つかりません: ${path}\n取得手順:\n  1. AppSheet Editor で対象アプリを開く\n  2. F12 → Network → HAR 保存\n  3. appsheet_import_har で HAR を渡してスナップショット化`,
    );
  }
  const app = await loadFromFile(path);
  cache.set(appId, app);
  log.info("appdef loaded", { path, id: app.Id });
  return app;
}

function extractEvalSource(e: Evaluatable | null | undefined): string | null {
  if (!e) return null;
  return e.SourceExpr ?? null;
}

function parseEnumValues(typeAuxRaw?: string): string[] | undefined {
  if (!typeAuxRaw) return undefined;
  try {
    const aux = JSON.parse(typeAuxRaw) as Record<string, unknown>;
    if (Array.isArray(aux.Values)) return aux.Values as string[];
    if (Array.isArray(aux.PossibleValues)) return aux.PossibleValues as string[];
  } catch {
    // ignore
  }
  return undefined;
}

interface ColumnSummary {
  name: string;
  type: string;
  displayName?: string;
  description?: string;
  isKey: boolean;
  isVirtual: boolean;
  isRequired: boolean;
  isHidden: boolean;
  isReadOnly: boolean;
  isAutoGenerated: boolean;
  isLabel: boolean;
  searchable: boolean;
  formula?: string | null;
  initialValue?: string | null;
  enumValues?: string[];
  resetOnEdit?: boolean;
}

interface ActionSummary {
  name: string;
  displayName?: string;
  table?: string;
  scope?: string;
  icon?: string;
  columnToEdit?: string;
  value?: string | null;
  condition?: string | null;
  comment?: string;
  inputCount: number;
}

interface ViewSummary {
  name: string;
  displayName?: string;
  table?: string;
  type?: string;
  position?: string;
  showIf?: string | null;
  description?: string;
}

function findSchema(app: RawApp, tableName: string): RawSchema | undefined {
  if (!app.AppData.DataSchemas) return undefined;
  const exact = app.AppData.DataSchemas.find((s) => s.AutoSchemaFrom === tableName);
  if (exact) return exact;
  return app.AppData.DataSchemas.find((s) => s.Name === `${tableName}_Schema`);
}

function summarizeColumn(a: RawAttribute): ColumnSummary {
  return {
    name: a.Name,
    type: a.Type ?? "Unknown",
    displayName: a.DisplayName || undefined,
    description: a.Description || undefined,
    isKey: !!a.IsKey,
    isVirtual: !!a.IsVirtual,
    isRequired: !!a.IsRequired,
    isHidden: !!a.IsHidden,
    isReadOnly: !!a.IsReadOnly,
    isAutoGenerated: !!a.IsAutoGenerated,
    isLabel: !!a.IsLabel,
    searchable: !!a.Searchable,
    formula: a.Formula ?? extractEvalSource(a.AppFormula),
    initialValue: a.Default ?? extractEvalSource(a.DefaultExpression),
    enumValues: parseEnumValues(a.TypeAuxData),
    resetOnEdit: a.ResetOnEdit || undefined,
  };
}

function summarizeAction(a: RawAction): ActionSummary {
  return {
    name: a.Name,
    displayName: a.DisplayName || undefined,
    table: a.Table || undefined,
    scope: a.Scope || a.TableScope || undefined,
    icon: a.Icon || undefined,
    columnToEdit: a.ColumnToEdit || undefined,
    value: a.Value ?? extractEvalSource(a.ValueEvaluatable),
    condition: a.Condition ?? extractEvalSource(a.ConditionEvaluatable),
    comment: a.Comment || undefined,
    inputCount: Array.isArray(a.Inputs) ? a.Inputs.length : 0,
  };
}

function summarizeView(c: RawControl): ViewSummary {
  return {
    name: c.Name,
    displayName: c.DisplayName || undefined,
    table: c.TableOrFolderName || undefined,
    type: c.ActionType || undefined,
    position: c.Position || undefined,
    showIf: c.ShowIf ?? null,
    description: c.Description || undefined,
  };
}

interface HarLog {
  log: { entries: Array<{ request: { url: string }; response: { content?: { text?: string; size?: number } } }> };
}

export async function importHar(args: { path: string; appId?: string }): Promise<{ savedTo: string; appId: string; tables: number; actions: number; views: number; }> {
  const harPath = resolve(args.path);
  const harText = await readFile(harPath, "utf8");
  const har = JSON.parse(harText) as HarLog;
  const entry = har.log.entries.find(
    (e) => /\/api\/loadApp\//.test(e.request.url) && (e.response.content?.size ?? 0) > 50000,
  );
  if (!entry?.response.content?.text) {
    throw new Error(`HAR に loadApp レスポンス（>50KB）が見つかりません: ${harPath}`);
  }
  const wrapper = JSON.parse(entry.response.content.text) as { app: string };
  if (typeof wrapper.app !== "string") {
    throw new Error(`loadApp レスポンスの構造が想定と違います（app 文字列フィールドなし）`);
  }
  const app = JSON.parse(wrapper.app) as RawApp;
  const credential = resolveCredential(args.appId ?? app.Id);
  if (app.Id && credential.appId !== app.Id) {
    log.warn("App ID 不一致", { fromHar: app.Id, fromEnv: credential.appId });
  }
  const out = snapshotPath(credential.appId);
  await mkdir(dirname(out), { recursive: true });
  await writeFile(out, JSON.stringify(app, null, 2), "utf8");
  cache.set(credential.appId, app);
  return {
    savedTo: out,
    appId: credential.appId,
    tables: app.AppData.DataSets?.length ?? 0,
    actions: app.AppData.DataActions?.length ?? 0,
    views: app.Presentation.Controls?.length ?? 0,
  };
}

export async function loadAppDef(args: { appId?: string; path?: string }): Promise<{ appId: string; title?: string; version?: string; tables: number; actions: number; views: number; bots: number; }> {
  const credential = resolveCredential(args.appId);
  const app = await ensureLoaded(credential.appId, args.path);
  return {
    appId: app.Id,
    title: app.Title || app.ShortName,
    version: app.Version,
    tables: app.AppData.DataSets?.length ?? 0,
    actions: app.AppData.DataActions?.length ?? 0,
    views: app.Presentation.Controls?.length ?? 0,
    bots: app.Behavior.AppBots?.length ?? 0,
  };
}

export async function getAppMetadata(args: { appId?: string }): Promise<{
  id: string;
  shortName?: string;
  title?: string;
  description?: string;
  version?: string;
  tables: string[];
}> {
  const credential = resolveCredential(args.appId);
  const app = await ensureLoaded(credential.appId);
  return {
    id: app.Id,
    shortName: app.ShortName,
    title: app.Title || undefined,
    description: app.Description || undefined,
    version: app.Version,
    tables: (app.AppData.DataSets ?? []).map((d) => d.Name),
  };
}

export async function getFullColumns(args: { appId?: string; tableName: string }): Promise<ColumnSummary[]> {
  const credential = resolveCredential(args.appId);
  const app = await ensureLoaded(credential.appId);
  const sch = findSchema(app, args.tableName);
  if (!sch) {
    const known = (app.AppData.DataSchemas ?? []).map((s) => s.AutoSchemaFrom || s.Name).join(", ");
    throw new Error(`スキーマ '${args.tableName}' が見つかりません。利用可能: ${known}`);
  }
  return (sch.Attributes ?? []).map(summarizeColumn);
}

export async function getActions(args: { appId?: string; tableFilter?: string; nameContains?: string }): Promise<ActionSummary[]> {
  const credential = resolveCredential(args.appId);
  const app = await ensureLoaded(credential.appId);
  let actions = (app.AppData.DataActions ?? []).map(summarizeAction);
  if (args.tableFilter) {
    actions = actions.filter((a) => a.table === args.tableFilter);
  }
  if (args.nameContains) {
    const q = args.nameContains.toLowerCase();
    actions = actions.filter((a) => a.name.toLowerCase().includes(q));
  }
  return actions;
}

export async function getActionDetail(args: { appId?: string; name: string }): Promise<RawAction> {
  const credential = resolveCredential(args.appId);
  const app = await ensureLoaded(credential.appId);
  const found = (app.AppData.DataActions ?? []).find((a) => a.Name === args.name);
  if (!found) throw new Error(`Action '${args.name}' が見つかりません`);
  return found;
}

export async function getViews(args: { appId?: string; tableFilter?: string }): Promise<ViewSummary[]> {
  const credential = resolveCredential(args.appId);
  const app = await ensureLoaded(credential.appId);
  let views = (app.Presentation.Controls ?? []).map(summarizeView);
  if (args.tableFilter) views = views.filter((v) => v.table === args.tableFilter);
  return views;
}

export async function getBots(args: { appId?: string }): Promise<{ count: number; items: unknown[] }> {
  const credential = resolveCredential(args.appId);
  const app = await ensureLoaded(credential.appId);
  const items = app.Behavior.AppBots ?? [];
  return { count: items.length, items };
}
